# 数据库连接使用教程

我们提供了方便的内置函数进行数据库的操作

## 取出一列数据

In [1]:
column = 'qe1' # 想要操作的列

In [2]:
data = sql(f"SELECT {column} FROM adult_2010") # 使用 sql 函数可以执行查询，返回的是 pandas 的 DataFrame 格式
data

       qe1
0        1
1        1
2        2
3        2
4        2
...    ...
33593    5
33594    1
33595    2
33596    2
33597    2

[33598 rows x 1 columns]

## 分组统计

In [3]:
data_counts = data.value_counts()
data_counts

qe1
 2     26741
 1      4338
 5      1975
 4       439
 3        96
-8         5
-1         3
-2         1
dtype: int64

## 查看数据的含义

In [4]:
schema = cfps2010.adult.schema['qe1']
schema

{'type': 'enum',
 'key': '请问您现在的婚姻状态是',
 'range': {'-10': '无法判断',
  '-9': '缺失',
  '-8': '不适用',
  '-2': '拒绝回答',
  '-1': '不知道',
  '0': '没有数据',
  '1': '未婚',
  '2': '在婚（有配偶）',
  '3': '同居',
  '4': '离婚',
  '5': '丧偶'},
 'details': [],
 'minmax': [-8.0, 5.0]}

## 可视化

In [5]:
chart = Pie()
chart.add('', [(schema["range"][str(i)], int(data_counts[i])) for i in range(1, 5+1)])
chart.set_global_opts(title_opts=opts.TitleOpts(title="2010年婚姻状态统计"))
chart.set_colors(["skyblue", "hotpink", "orange", "green", "black"])
chart.render_notebook()

## 显示数据库中的表格

In [6]:
sql("SHOW TABLES")

            Tables_in_cfps
0               adult_2010
1         adult_2010_clean
2               adult_2011
3               adult_2012
4         adult_2012_clean
5               adult_2014
6         adult_2014_clean
7               adult_2016
8         adult_2016_clean
9               child_2010
10        child_2010_clean
11       child_2010_infant
12              child_2011
13              child_2012
14        child_2012_clean
15       child_2012_infant
16              child_2014
17        child_2014_clean
18       child_2014_infant
19              child_2016
20        child_2016_clean
21       child_2016_infant
22         childproxy_2018
23   childproxy_2018_clean
24  childproxy_2018_infant
25               comm_2010
26         comm_2010_clean
27               comm_2014
28         comm_2014_clean
29        crossyearid_2018
30            famconf_2010
31            famconf_2012
32            famconf_2014
33            famconf_2016
34            famconf_2018
35            famecon_2010
36       famecon_2010_agri
37      famecon_2010_clean
38    famecon_2010_company
39            famecon_2012
40       famecon_2012_agri
41      famecon_2012_clean
42    famecon_2012_company
43            famecon_2014
44       famecon_2014_agri
45      famecon_2014_clean
46    famecon_2014_company
47            famecon_2016
48       famecon_2016_agri
49      famecon_2016_clean
50    famecon_2016_company
51            famecon_2018
52       famecon_2018_agri
53      famecon_2018_clean
54    famecon_2018_company
55             family_2011
56          famroster_2011
57             person_2018
58       person_2018_clean

## 尝试破坏数据库 （安全性控制）

我们对数据库进行了安全加固，当前的用户没有篡改数据库的权限，这保证了数据的可靠性和安全性，如果你尝试进行非法操作，会直接报错

In [7]:
sql("DROP TABLE adult_2010")

OperationalError: (pymysql.err.OperationalError) (1142, "DROP command denied to user 'jupyterhub'@'172.17.0.2' for table 'adult_2010'")
[SQL: DROP TABLE adult_2010]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

## 尝试篡改数据

In [8]:
sql("update adult_2012 set qe1=233 where pid12=12312354134")

OperationalError: (pymysql.err.OperationalError) (1142, "UPDATE command denied to user 'jupyterhub'@'172.17.0.2' for table 'adult_2012'")
[SQL: update adult_2012 set qe1=233 where pid12=12312354134]
(Background on this error at: https://sqlalche.me/e/14/e3q8)